window_title: "Interactive phonon visualizer"
page_title: "Interactive phonon visualizer"

#custom_css_files:
# input_data:
#    - custom.css
#  process_data:
#    - custom.css

#custom_js_files:
#  input_data:
#  process_data:
#    - custom.js

about_section_title: "About Interactive phonon visualizer"

templates:
  how_to_cite: null
  about: "custom_about.html"
  select_content: "visualizer_select_structure.html"

use_upload_structure_block: False

additional_accordion_entries:
  - header: "Acknowledgements"
    template_page: ack.html

data_folder: "user_static/data/"

data:
  Bi2:
    title: "Bi<sub>2</sub>"
    filename: Bi2.json
  BN:
    title: "BN"
    filename: BN.json
  C2:
    title: "C<sub>2</sub>"
    filename: C2.json
  CoH2O2:
    title: "CoH<sub>2</sub>O<sub>2</sub>"
    filename: CoH2O2.json
  I2Pb:
    title: "I<sub>2</sub>Pb"
    filename: I2Pb.json
  MoS2:
    title: "MoS<sub>2</sub>"
    filename: MoS2.json
  P4:
    title: "P<sub>4</sub>"
    filename: P4.json
  PbTe:
    title: "PbTe"
    filename: PbTe.json
