window_title: "Interactive phonon visualizer"
page_title: "Interactive phonon visualizer"

#custom_css_files:
# input_data:
#    - custom.css
#  process_data:
#    - custom.css

#custom_js_files:
#  input_data:
#  process_data:
#    - custom.js

about_section_title: "About Interactive phonon visualizer"

templates:
  how_to_cite: null
  about: "custom_about.html"
  select_content: "visualizer_select_structure.html"

use_upload_structure_block: False

additional_accordion_entries:
  - header: "Acknowledgements"
    template_page: ack.html

